trigger-development:
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'
  trigger:
    include:
      - project: '${PROJECT_PROVISIONER_APPLICATION}'
        file: 'horizon-charts-dev/.development_uptime.yml'
    strategy: depend
 
trigger-staging:
  rules:
    - if: '$CI_COMMIT_BRANCH == "staging"'
  trigger:
    include:
      - project: '${PROJECT_PROVISIONER_APPLICATION}'
        file: 'horizon-charts-dev/.staging_uptime.yml'
    strategy: depend

trigger-homolog:
  rules:
    - if: '$CI_COMMIT_BRANCH == "homolog"'
  trigger:
    include:
      - project: '${PROJECT_PROVISIONER_APPLICATION}'
        file: 'horizon-charts-dev/.homolog_uptime.yml'
    strategy: depend

trigger-production:
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  trigger:
    include:
      - project: '${PROJECT_PROVISIONER_APPLICATION}'
        file: 'horizon-charts-dev/.production_uptime.yml'
    strategy: depend