name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  CI:
    runs-on:  ubuntu-latest
    steps:
    - name: Checking code
      uses: actions/checkout@v4.1.7
    - name: Docker Hub Autentication
      uses: docker/login-action@v3.3.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
