name: first-pipeline
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  first-job:
    name: "My first Job"
    runs-on: ubuntu-latest
    steps:
      - name: "My first action"
        run: echo "Hello World !!"
      - name: "My second action"
        run: |
          echo "You created your first workflow !!"
          echo "Congratulations!"
      - name: "My python action"
        run: |
          x = "My script python"
          print(x)
        shell: python
  second-job:
    name: "My second job"
    runs-on: ubuntu-latest
    steps:
      - name: "Check node verison"
        run: node --version
      - name: "Use marketplace actions"
        uses: actions/setup-node@v4.0.3
        with:
         node-version: '22.7.0'
      - name: "Check node verison"
        run: node --version
